config/routes.rb
Rails.application.routes.draw do

  root "customers/homes#top"
  get "/about" => "customers/homes#about"

  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do # => /admin/items etc
    resources :items
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      collection do
        get :today_index
      end
      member do
        get :customer_index
      end
    end
    
    resources :order_details, only: [:update]
    get "" => "home#top"
  end
  


  scope module: :customers do
    resources :items, only: [:index, :show] do
      collection do
        get :sort
      end
    end
    resources :customers
    resources :addresses, except: [:new, :show]
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'thanks'
      end
    end
    get "/customers/:id" => "customers#show"
    get "/customers/:id/quit" => "customers#quit", as: 'customers_quit'
    put "/customers/:id/out" => "customers#out", as: 'customers_out'
    get "/customers/:id/edit" => "customers#edit"

    resources :cart_items, only: [:create, :index, :destroy, :update]
    delete 'cart_items' => 'cart_items#all_destroy', as: 'cart_all_destroy'
    
  end



end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :orders

  has_many :cart_items
  has_many :items
  has_many :orders, dependent: :destroy

  def full_name
    last_name + first_name
  end

  def full_name_kana
    last_name_kana + first_name_kana
  end

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :postal_code, presence: true, numericality: { only_integer: true, message: "は半角数字で入力して下さい。" }
	validates :address, presence: true
	validates :phone_number, presence: true, numericality: { only_integer: true, message: "は半角数字で入力して下さい。" }

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    
    if @customer.update(customer_params)
      redirect_to admin_customer_path
    else
      render "edit"
    end
  end

  private
  def customer_params
    params.require(:customer).permit(
      :first_name, :last_name, :first_name_kana,
      :last_name_kana, :postal_code, :address,
      :phone_number, :email, :is_deleted
      )
  end

end

app/controllers/customers/addresses_controller.rb
class Customers::AddressesController < Customers::ApplicationController

  def index
    @customer = current_customer
    @address = Address.new
    @addresses = @customer.addresses
  end

  def create
    @customer = current_customer
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    @addresses = @customer.addresses
    if @address.save
      redirect_to addresses_path
    else
      render "index"
    end
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
      redirect_to addresses_path
    else
      render "edit"
    end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to addresses_path
  end

  private

  def address_params
    params.require(:address).permit(:name, :postal_code, :address)
  end

end

app/controllers/customers/application_controller.rb
class Customers::ApplicationController < ApplicationController
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :name,
      ])
  end
end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
  
  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    if cart_item = current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id])
       cart_item.amount += params[:cart_item][:amount].to_i
       cart_item.save
       flash[:notice] = "Item was successfully added to cart."
       redirect_to cart_items_path
    elsif @cart_item.save
          flash[:notice] = "New Item was successfully added to cart."
          redirect_to cart_items_path
    else
       redirect_to cart_items_path
    end
  end
  
  def index
    @cart_items = current_customer.cart_items.all
  end
  
  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    flash[:notice] = "商品の数量を変更しました。"
    redirect_to cart_items_path
  end
  
  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    flash[:notice] = "商品を削除しました。"
    redirect_to cart_items_path
  end
  
  def all_destroy
    current_customer.cart_items.destroy_all
    flash[:alert] = "カート内の商品を全て削除しました。"
    redirect_to cart_items_path
  end

private
  def cart_item_params
      params.require(:cart_item).permit(:customer_id, :item_id, :amount)
  end
  
end

# cart_item_params[:amount]
# params[:cart_item][:amout]

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
  
  def show
    @customer = current_customer
  end
  
  def edit
    @customer = current_customer
  end
  
  def update
    @customer = current_customer
    if @customer.update(customer_params)
       flash[:success] = "登録情報を変更しました"
       redirect_to customer_path
    else
      render :edit and return
    end
  end
  
  def quit
  end
  
  def out
    @customer = current_customer
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end
  
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :address, :phone_number)
  end
end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < Customers::ApplicationController
  def top
    @genres = Genre.where(is_active: true)
    @items = Item.last(4)
  end

  def about
  end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < Customers::ApplicationController
  before_action :authenticate_customer!, only: [:show]
  
  def index
    @items = Item.page(params[:page]).per(8)
    @genres = Genre.where(is_active: true)
  end
  
  def sort
    @items = Item.where(genre_id: params[:genre_id])
    @genres = Genre.where(is_active: true)
    @genre = Genre.find(params[:genre_id])
  end
  
  def show
    @item = Item.find(params[:id])
    @genres = Genre.where(is_active: true)
    @include_tax = (@item.price * 1.1).round
    @cart_item = CartItem.new
  end
  
  private
  def item_params
      params.require(:item).permit(:genre_id, :name, :introduction, :price, :image_id, :is_active)
  end
  
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < Customers::ApplicationController
  def new
    @customer = current_customer
    @order = Order.new
    @address = Address.new
    @addresses = @customer.addresses
  end

  def confirm
    @order = Order.new(order_params)
    @order_detail = OrderDetail.new
    @cart_items = current_customer.cart_items.all
    @order.shipping_cost = 800

    if params[:order][:address_option] == "0"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.full_name

    elsif params[:order][:address_option] == "1"
      @address_id = params[:order][:address_id].to_i
      @address = Address.find(@address_id)
      @order.postal_code = @address.postal_code
      @order.address = @address.address
      @order.name = @address.name

    elsif params[:order][:address_option] == "2"
      @address = Address.new(address_params)
      @address.customer_id = current_customer.id
      @address.save
      @order.postal_code = @address.postal_code
      @order.address = @address.address
      @order.name = @address.name
      @address.save
    end

  end

  def create
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id
    @order.save

    current_customer.cart_items.all.each do |cart_item|
      order_detail = OrderDetail.new
      order_detail.order_id = @order.id
      order_detail.item_id = cart_item.item.id
      order_detail.amount = cart_item.amount
      order_detail.price = cart_item.item.price * 110 / 100
      order_detail.save
    end

    current_customer.cart_items.destroy_all

    redirect_to thanks_orders_path

  end

  def thanks
  end

  def index
    @orders = current_customer.orders.all
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  private

  def order_params
    params.require(:order).permit(:shipping_cost, :total_payment,
    :payment_method, :name, :postal_code, :address, :status)
  end

  def address_params
    params.require(:address).permit(:name, :postal_code, :address)
  end

end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end


  before_action :reject_customer, only: [:create]


  protected

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_customer_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/customers/cart_items_helper.rb
module Customers::CartItemsHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="body">
  <div class="container">
    <h2><%= @customer.full_name %>さんの会員情報編集</h2>
    
    

    <%= form_with(model: @customer, url: admin_customer_path(@customer)) do |f| %>

      <div class="form-group">
        <%= f.label :名前 %>
        <br>
        <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", placeholder: "性" %>
        <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", placeholder: "名" %>
      </div>

      <div class="form-group">
        <%= f.label :フリガナ %>
        <br>
        <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana", placeholder: "セイ" %>
        <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana", placeholder: "メイ" %>
      </div>

      <div class="form-group">
        <%= f.label :メールアドレス %><br />
        <%= f.email_field :email %>
      </div>

      <div class="form-group">
        <%= f.label :郵便番号 %>
        <br>
        <%= f.text_field :postal_code %>
      </div>

      <div class="form-group">
        <%= f.label :住所 %>
        <br>
        <%= f.text_field :address %>
      </div>

      <div class="form-group">
        <%= f.label :電話番号 %>
        <br>
        <%= f.text_field :phone_number %>
      </div>

      <br>

      <div class="form-group">
        <%= f.label :有効 %><%= f.radio_button :is_deleted, false %>
        <%= f.label :退会済み %><%= f.radio_button :is_deleted, true %>
      </div>

      <br>

      <div class="actions">
        <%= f.submit '変更を保存する', class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="body">
  <div class="container">
    <div class="row">

      <h2>会員一覧</h2>
      <table class="table table-inverse">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td>
                <%= customer.id %>
              </td>
              <td>
                <%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id) %>
              </td>
              <td>
                <%= customer.email %>
              </td>
              <td>
                <% if customer.is_deleted == false %>
                  <p>有効会員</p>
                <% else %>
                  <p>退会済み</p>
                <% end %>
              </td>
            </tr>
          <% end %>

        </tbody>
      </table>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="body">
  <div class="container">
    <div class="row">

      <h2><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h2>
      <br>
      <table class="table">
        <tbody>
          <tr>
            <th>顧客ID</th>
            <th>
              <%= @customer.id %>
              <% if @customer.is_deleted == false %>
                <p>有効会員</p>
              <% else %>
                <p>退会済み</p>
              <% end %>
            </th>
          </tr>
          <tr>
            <th>氏名</th>
            <th><%= @customer.last_name + "　" + @customer.first_name %></th>
          </tr>
          <tr>
            <th>フリガナ</th>
            <th><%= @customer.last_name_kana + "　" + @customer.first_name_kana %></th>
          </tr>
          <tr>
            <th>郵便番号</th>
            <th><%= @customer.postal_code %></th>
          </tr>
          <tr>
            <th>住所</th>
            <th><%= @customer.address %></th>
          </tr>
          <tr>
            <th>電話番号</th>
            <th><%= @customer.phone_number %></th>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <th><%= @customer.email %></th>
          </tr>
        </tbody>
      </table>
      <div>
        <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-primary" %>
      </div>
      <br>
      <div>
        <%= link_to "注文履歴一覧を見る", customer_index_admin_order_path(customer_id: @customer.id), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/update.html.erb
<h1>Customers#update</h1>
<p>Find me in app/views/customers/update.html.erb</p>