config/routes.rb
Rails.application.routes.draw do

  root "customers/homes#top"
  get "/about" => "customers/homes#about"

  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    registrations: 'customers/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do # => /admin/items etc
    resources :items
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      collection do
        get :today_index
      end
      member do
        get :customer_index
      end
    end
    
    resources :order_details, only: [:update]
    get "" => "home#top"
  end
  


  scope module: :customers do
    resources :items, only: [:index, :show] do
      collection do
        get :sort
      end
    end
    resources :customers
    resources :addresses, except: [:new, :show]
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'thanks'
      end
    end
    get "/customers/:id" => "customers#show"
    get "/customers/:id/quit" => "customers#quit", as: 'customers_quit'
    put "/customers/:id/out" => "customers#out", as: 'customers_out'
    get "/customers/:id/edit" => "customers#edit"

    resources :cart_items, only: [:create, :index, :destroy, :update]
    delete 'cart_items' => 'cart_items#all_destroy', as: 'cart_all_destroy'
    
  end



end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details

  belongs_to :customer
  enum payment_method: {クレジットカード:0, 銀行振込:1}
  enum status: { 入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4 }
  
  validates :name, presence: true
	validates :postal_code, presence: true
	validates :address, presence: true

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def today_index
    @orders = Order.where(created_at: Time.now.in_time_zone.all_day)
  end
  
  def index
    @orders = Order.page(params[:page]).per(10).order(created_at: "DESC")
  end
  
  def customer_index
    @orders = Order.where(customer_id: params[:customer_id])
  end
  
  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id:[@order.id])
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path(@order)
  end
  
  private
  def order_params
    params.require(:order).permit(:status)
  end
  
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < Customers::ApplicationController
  def new
    @customer = current_customer
    @order = Order.new
    @address = Address.new
    @addresses = @customer.addresses
  end

  def confirm
    @order = Order.new(order_params)
    @order_detail = OrderDetail.new
    @cart_items = current_customer.cart_items.all
    @order.shipping_cost = 800

    if params[:order][:address_option] == "0"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.full_name

    elsif params[:order][:address_option] == "1"
      @address_id = params[:order][:address_id].to_i
      @address = Address.find(@address_id)
      @order.postal_code = @address.postal_code
      @order.address = @address.address
      @order.name = @address.name

    elsif params[:order][:address_option] == "2"
      @address = Address.new(address_params)
      @address.customer_id = current_customer.id
      @address.save
      @order.postal_code = @address.postal_code
      @order.address = @address.address
      @order.name = @address.name
      @address.save
    end

  end

  def create
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id
    @order.save

    current_customer.cart_items.all.each do |cart_item|
      order_detail = OrderDetail.new
      order_detail.order_id = @order.id
      order_detail.item_id = cart_item.item.id
      order_detail.amount = cart_item.amount
      order_detail.price = cart_item.item.price * 110 / 100
      order_detail.save
    end

    current_customer.cart_items.destroy_all

    redirect_to thanks_orders_path

  end

  def thanks
  end

  def index
    @orders = current_customer.orders.all
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  private

  def order_params
    params.require(:order).permit(:shipping_cost, :total_payment,
    :payment_method, :name, :postal_code, :address, :status)
  end

  def address_params
    params.require(:address).permit(:name, :postal_code, :address)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_list.html.erb
<table class="table table-bordered table-condensed">
  <thead>
    <tr>
      <th>購入日時</th>
      <th>購入者</th>
      <th>注文個数</th>
      <th>注文ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% orders.each do |order| %>
    <tr>
      <td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order) %></td>
      <td><%= order.name %></td>
      <td>
        <% order_details = OrderDetail.where(order_id:[order.id]) %>
        <% count = 0 %>
        <% order_details.each do |order_detail| %>
          <% count += order_detail.amount %>
        <% end %>
        <%= count %>
      </td>
      <td><%= order.status %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/orders/customer_index.html.erb
<div class="container">
  <div class="row">
    <h2>注文履歴一覧</h2>
    <div class="col-md-12">
      
      <%= render 'list', orders: @order %>
      
    </div>
    <%= link_to '注文履歴一覧', admin_orders_path %>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <h2>注文履歴一覧</h2>
    <div class="col-md-12">
      
      <%= render 'list', orders: @orders %>
      
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <h2>注文履歴詳細</h2>
    <div class="col-md-12">
      <div class="row">購入者  <%= link_to @order.name, admin_customer_path(@order.customer) %></div>
      <div class="row">配送先  〒<%= @order.postal_code + @order.address + @order.name %></div>
      <div class="row">支払い方法  <%= @order.payment_method %></div>
      <div class="row">
        注文ステータス  
        <%= form_with model: @order, url: admin_order_path(@order), local: true do |f| %>
          <%= f.select :status, Order.statuses.keys %>
          <%= f.submit '更新', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-8">
      <table class="table">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.price %></td>
              <td><%= order_detail.amount %></td>
              <td><%= (order_detail.price * order_detail.amount) %></td>
              <td>
                <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), local: true do |f| %>
                  <%= f.select :making_status, OrderDetail.making_statuses.keys %>
                  <%= f.submit '更新', class: 'btn btn-primary' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-4">
      <br><br>
      <div class="row">商品合計  <%= @order.total_payment - @order.shipping_cost %>円</div>
      <div class="row">送料  <%= @order.shipping_cost %>円</div>
      <div class="row">請求金額合計  <%= @order.total_payment %>円</div>
    </div>
  </div>
  <%= link_to '注文履歴一覧', admin_orders_path %>
</div>

app/views/admin/orders/today_index.html.erb
<div class="container">
  <div class="row">
    <h2>今日の注文履歴一覧</h2>
    <div class="col-md-12">
      
      <%= render 'list', orders: @orders %>
      
    </div>
    <%= link_to '注文履歴一覧', admin_orders_path %>
  </div>
</div>